### ISSUE TITLE
Simple ignore patterns are applied even for subfolders.

### ISSUE THREAD

**Issue by artem-zinnatullin** [gojuno/mainframer#104]
Example `ignore`:

```
sample
```

Will ignore not only root (in the project) file or directory with name `sample`, but also any file or directory with name `sample` in any level of subfolders in the project.

This is not how file/directory patterns work in  `.gitignore` and other commonly used tools.

**Comment by artem-zinnatullin** [comment]
https://stackoverflow.com/questions/13713101/rsync-exclude-according-to-gitignore-hgignore-svnignore-like-filter-c

**Comment by artem-zinnatullin** [comment]
Looks like it's not that easy to change this behavior, we could of course manually read ignore files and add leading `/` if path does not include it already and then pass it to `--exclude` as parameters.

Otherwise we can note that in documentation and live with it.

**Comment by arturdryomov** [comment]
I think it is pretty safe just to reference `rsync` docs in our docs. I. e. we are using `rsync` file exclusion format for `*ignore` files. No need to reimplement what was already done for us.
