### ISSUE TITLE
IntelliJ Plugin.

### ISSUE THREAD

**Issue by artem-zinnatullin** [gojuno/mainframer#125]
At the moment you can integrate `mainframer` with IntelliJ pretty easily, but the process is manual and hard to scale in big teams.

The idea is to create a Plugin for IntelliJ that would be able to run exact same build commands that IntelliJ wants to run (triggered by hotkey/click) and pass them to `mainframer.sh` and then wait for output. That would make integration veery easy for basically any type of project in IntelliJ.

Currently we don't have resources to create such a plugin, so if someone would like to work on it or if we'll start it — please comment here so others could track the progress!

**Comment by ghostbuster91** [comment]
Hi all, I created a repository for this plugin, so PRs are welcome.
https://github.com/elpassion/mainframer-intelij-plugin

**Comment by artem-zinnatullin** [comment]
Subscribed!

**Comment by artem-zinnatullin** [comment]
Closing by #178. 

Guys from Elpassion did awesome work on a plugin, it supports any build system integrated with IntelliJ as well as custom build steps, highly recommended!
