### ISSUE TITLE
Can't run script

### ISSUE THREAD

**Issue by renegens** [gojuno/mainframer#132]
Hello,

I am trying to make this work but I am getting an error when I run `bash mainframer.sh ./gradlew build` . I have added to `.mainframer` the config files from the sample and my local.properties folder has the sdk path of the remote machine.

```
mainframer v1.1.2
Start time: Sat Jan 21 22:08:01 EET 2017
Please specify remote build machine in local.properties
```

**Comment by artem-zinnatullin** [comment]
Please switch to docs for v1.1.2 or use mainframer v2.0.0-dev from the
repo, we're in v2.0.0 preparing stage and docs you're seeing in repo are
for v2.

**Comment by artem-zinnatullin** [comment]
Closing issue for now, if you have any questions don't hesitate to ask here on in a separate issue.
