### ISSUE TITLE
Windows as remote machine

### ISSUE THREAD

**Issue by renegens** [gojuno/mainframer#157]
Hello,

great project you have running here. Had anybody success running this with windows  10 bash or under normal Windows just to utilize the gaming pc that is sitting?

**Comment by artem-zinnatullin** [comment]
Does it have rsync and ssh?

**Comment by renegens** [comment]
@artem-zinnatullin yes it has both of them but I have trouble setting up the ssh up until now. Has anybody else tried it?

**Comment by balachandarlinks** [comment]
Hi @renegens, you can set up a docker container with Linux on your windows machine. I have recently written this blog post which explains the Mainframer setup on a windows machine with docker container. It may be helpful to you.

Blog Post : https://medium.com/@balachandarkm/speed-up-android-builds-with-mainframer-docker-container-in-a-powerful-remote-machine-ce7b9e122a49

**Comment by renegens** [comment]
@balachandarlinks Thanks for pointing this out, will check it asap. Great post btw :)

**Comment by artem-zinnatullin** [comment]
@balachandarlinks like 👍 !

**Comment by artem-zinnatullin** [comment]
I'm closing this issue for now, to sum up: preferred software options on remote machine with Windows OS are Docker, VM with Linux or integrated "bash supported" (parts of Linux/Ubuntu environment).

Please feel free to comment into this issue or submit a PR with documentation on configuring Windows as remote machine for Mainframer.
