### ISSUE TITLE
Product flavor build fails

### ISSUE THREAD

**Issue by PaulWoitaschek** [gojuno/mainframer#160]
I have a very simple product flavor that just enables one configuration

```groovy
    productFlavors {
        allConfigs {}
        singleConfig {
            resConfigs "en", "xxhdpi"
        }
    }
```

When I now compile it like `./gradlew :audiobook:assembleSingleConfigDebug`,

the acutal compiling works but the deployment fails:

```
03/26 19:06:11: Launching remote
The APK file /Users/ph1b/Dev/MaterialAudiobookPlayer/audiobook/build/outputs/apk/173-MaterialAudiobookPlayer-allConfigs-debug-3.1.0-RC4.apk does not exist on disk.
Error while Installing APK
```

It complains about the `allConfigs` missing, which is expected because I did not pick that flavor.

**Comment by PaulWoitaschek** [comment]
I had to go to the build variants tab and select the flavor I was building on the remote machine.

**Comment by artem-zinnatullin** [comment]
Yup, Android Studio determines location of the apk to install through
Gradle Sync on local machine. We all have been there :)
