### ISSUE TITLE
Use intellij to compile without deployment target

### ISSUE THREAD

**Issue by PaulWoitaschek** [gojuno/mainframer#166]
Is it possible to configure intelij / AS to let the remote machine build and sync changes without a target device selected? 
While developing I don't always have a device connected and what I'm looking for is the `Build/Build APK` option.

**Comment by artem-zinnatullin** [comment]
Yes, this is totally possible! Easiest way to do is to use [elpassion/mainframer-intellij-plugin](https://github.com/elpassion/mainframer-intellij-plugin).

1. `Edit Configurations…`
1. `Add new configuration` → `Mainframer`
1. Give it a name
1. Set some build command, i.e.: `./gradlew :app:assembleDebug`

Now you can simply run it as regular `Run Configuration` with good log output right from IntelliJ.
