### ISSUE TITLE
Rename mainframer.sh to mainframer.

### ISSUE THREAD

**Issue by artem-zinnatullin** [gojuno/mainframer#169]
by most used convention for shell scripts (ie google style guides for shell scripts) they should be named without file extension.

cc @ghostbuster91 @pawegio

**Comment by artem-zinnatullin** [comment]
@ming13 let's make a PR to IntelliJ plugin first?

**Comment by artem-zinnatullin** [comment]
@ming13 what have we decided regarding "breaking change"? Is it one or it's not and I can go ahead and make a PR?

I'm using Mainframer in lots of personal projects (I have a Linux server at home now lol) and kinda want it to be a system wide tool already

**Comment by arturdryomov** [comment]
I think we can make a PR to the plugin before we prepare a next release. It allows to download the tool using our release tags, otherwise it is possible to change the path manually, so I think it is a pretty safe bet.

**Comment by ghostbuster91** [comment]
Since plugin is basing on release tags as @ming13 noticed will you rename previous artifacts to not contains `.sh` or should we drop support for 2.x versions?

**Comment by artem-zinnatullin** [comment]
No, we won't rename previous artifacts (releases are immutable for us).

It's up to you though whether to support or drop 2.x versions in IntelliJ Plugin, but we will definitely update Mainframer version to 3.x with this change since it's a breaking change for automation and IntelliJ Plugin
