### ISSUE TITLE
Uses wrong project

### ISSUE THREAD

**Issue by PaulWoitaschek** [gojuno/mainframer#172]
My audiobook player uses the Android NDK in the current versions.

https://github.com/PaulWoitaschek/MaterialAudiobookPlayer/blob/master/exoplayer-opus/build.gradle#L44

Therefore I pass the NDK dir to a custom task in the buildSrc folder:

```
task(prepareOpus, type: PrepareOpus) {
    ndkDir = project.extensions.findByName("android").ndkDirectory
}
```

However now mainframer uses the NDK directory of my host machine, not my remote machine and therefore fails the build.

**Comment by artem-zinnatullin** [comment]
How do you build project with Mainframer?

I guess path to ndk gets written to some file that is synched by mf and then Gradle tries to use that path on remote machine, we had similar problem with Kotlin compilation and JB fixed that.

**Comment by PaulWoitaschek** [comment]
> How do you build project with Mainframer?

I just do a `./mainframer.sh ./gradlew assembleRelease`. I don't get the question, are there other ways for building a project with mainframer?

**Comment by artem-zinnatullin** [comment]
Well I was hoping that mistake was easy like `./mainframer.sh ./gradlew assembleRelease -Pndk-path=path_on_local_machine` :)

Can you please try to find ndk path in some files in the project that might be synched to remote machine? 

Something like `grep -R "path_to_ndk_on_local_machine" ./` in project directory on local machine? Or even better — `cmd + F` in project directory in IntelliJ?

There are no other ways for Gradle on remote machine to pick up some property from local machine except from a file!

**Comment by PaulWoitaschek** [comment]
I can't replicate it rigth now. When it happens again I'll reopen. Damn quantums :D

**Comment by artem-zinnatullin** [comment]
Did you run gradlew clean? I believe it only happens when you've built
project locally and then tried to build it remotely.
