### ISSUE TITLE
Rebuild and Make project commands (idea plugin)

### ISSUE THREAD

**Issue by edwardstock** [gojuno/mainframer#179]
Hi! How can be achieved rebuilding and making project inside Idea (android studio) ?
What i did: 
* installed Idea plugin
* Configured project, app run/debug working properly
* Run Configuration (Mainframer) selected as default

But, for example. I'm doing custom view, after some changes in this view, idea prints error "custom view has been edited more recently[...]. Build the project". When i click build, project builds locally. Ok, i tried to just execute manually `mainframer remote-build-cmd-blah`, project builds successfully, but idea still not refreshing this info (i don't know what) and still prints me error.

Maybe i'm doing something wrong?

**Comment by artem-zinnatullin** [comment]
Can you please create an issue in IntelliJ Plugin repo https://github.com/elpassion/mainframer-intellij-plugin?

We'll follow up there, if it can't be solved by plugin, we should probably create ticket against Android Studio as it doesn't sync file changes properly.

**Comment by artem-zinnatullin** [comment]
I'm closing issue in this repo, please just copy-paste it to https://github.com/elpassion/mainframer-intellij-plugin and crosslink them for discoverability, thanks!

**Comment by edwardstock** [comment]
Thank you! By the way, refreshing issue solved just after restart android studio (3.0 beta 2).

**Comment by artem-zinnatullin** [comment]
Great, thanks for update!
