### ISSUE TITLE
How do I specify the gradle task based on current build variant selected?

### ISSUE THREAD

**Issue by bhargavms** [gojuno/mainframer#183]
So android studio has option to select build variants, and gradle aware make - performs compilation for that variant, how do I have similar behavior using mainframer?

**Comment by artem-zinnatullin** [comment]
We recommend you to use [Mainframer IntelliJ Plugin](https://github.com/elpassion/mainframer-intellij-plugin) from elpassion.

I think they recently added macros support for exact same reason, please check:

- Issue https://github.com/elpassion/mainframer-intellij-plugin/issues/170
- PR https://github.com/elpassion/mainframer-intellij-plugin/pull/175

Solution should be part of Mainfraimer IntelliJ Plugin [v1.2.1](https://github.com/elpassion/mainframer-intellij-plugin/releases/tag/v1.2.1).

If you still have issue (for instance I don't really see documentation about marcos), please open issue/PR in their repo and crosslink it with this issue for discoverability.

I understand that this is real use case, but it's not really about Mainframer itself but more of integration with 3rd-party tools like IntelliJ Idea.

Thanks!

**Comment by bhargavms** [comment]
@artem-zinnatullin thank you for the swift response will take look at the links!
