### ISSUE TITLE
Deploy Mainframer binaries to GitHub releases.

### ISSUE THREAD

**Issue by artem-zinnatullin** [gojuno/mainframer#198]
Since we now use compiled language #191, we need to ship binaries instead of source code.

To do that I'm planning to deploy resulting binaries to GitHub releases which can be either manually downloaded or installed through Homebrew/etc. Later we could also upload binaries to Bintray to have them there just in case.

As a reference example, this is how `ripgrep` does it:

- [ripgrep GitHub releases page](https://github.com/BurntSushi/ripgrep/releases)
- [ripgrep Homebrew](https://github.com/BurntSushi/ripgrep/blob/f5411b992cb5287e35ceca724651121c0beb3995/pkg/brew/ripgrep-bin.rb)
- [ripgrep Travis config that deploys to GitHub](https://github.com/BurntSushi/ripgrep/blob/f5411b992cb5287e35ceca724651121c0beb3995/.travis.yml#L89)

And Travis documentation about deploying to GitHub releases https://docs.travis-ci.com/user/deployment/releases/

**Comment by artem-zinnatullin** [comment]
@ming13 I'm thinking about deploying `3.0.0-alpha-1` so we could start preparing Homebrew formulae #32 , #185 and you could start ~~dogfood~~ using Rust version at Juno

So then later we could deploy update with #188 or #189 and check update mechanism

wdut?

**Comment by arturdryomov** [comment]
Sure, let’s do it.
