### ISSUE TITLE
Reflect current state of project in the README.

### ISSUE THREAD

**Issue by artem-zinnatullin** [gojuno/mainframer#210]
People are getting confused on what happened with Bash version after we rewrote it in Rust #191 (I got emails) and which version should be used at the moment.

We should add a section to the README that'll reflect current state of the 3.x development, suggest to keep using 2.x until we release 3.x and how to try 3.x builds.

**Comment by arturdryomov** [comment]
Damn, we should have used a `3.x` branch :-(
