### ISSUE TITLE
Configuration files format.

### ISSUE THREAD

**Issue by artem-zinnatullin** [gojuno/mainframer#225]
Just want to get discussion around configuration files format we use.

Right now it's https://en.wikipedia.org/wiki/.properties, which is fast to parse and easy to read & write.

However it's not super common among other tools and it doesn't have a standartized way to have sections in it and it doesn't look very structured. However I like that it maps 1:1 with command-line args we'll be adding in 3.x.

Possible alternatives:

- [YAML](https://en.wikipedia.org/wiki/YAML) (not a fan, but it's very popular nowadays)
- [JSON](https://en.wikipedia.org/wiki/JSON) (doesn't have comments but easy to work with)
- [INI](https://en.wikipedia.org/wiki/INI_file) (very similar to `.properties`, but has sections, also not very popular)

Or we can keep everything as is of course :)

Wonder what our users think, especially given that in 3.x we'll introduce global config files and maybe couple more. cc @ming13

**Comment by artem-zinnatullin** [comment]
Actually, I'm wrong, configuration file keys won't 1:1 match commandline arguments. 

ie 

```properties
remote_machine=test@machine
```

vs 

```console
mainframer --remote-machine test@machine
```

**Comment by lukaville** [comment]
What do you think about https://github.com/lightbend/config?

**Comment by arturdryomov** [comment]
I’m going to throw [TOML](https://github.com/toml-lang/toml) in.

**Comment by matthoffman** [comment]
as an outside observer, I'd suggest YAML, because:
1. it maps cleanly to JSON (it's a superset of JSON), so it's easy to convert it to JSON for machine use. But it's much more readable and easier to write than JSON, of course.
2. it has comments, which I think is pretty essential for a config file
3. it's widely supported by libraries and tooling
4. it's the default for docker, kubernetes, and many other devops-ish kinds of tools, so it feels "familiar".
5. it would be fairly easy (if there's demand) to add support for .properties and/or INI later, as an alternate input format.

**Comment by artem-zinnatullin** [comment]
As much as I hate YAML working with it on daily basis, I think that's right choice as it covers all our current and potential future needs and has a lot of examples and docs in case someone has problems with it.

@ming13 if you don't have strong objections, I'll start working on it, I need to figure the format before I can start working on #213 and configs merging

---

For sake of mentioning couple more alternatives:

- Dhall https://github.com/dhall-lang/dhall-lang
- ~~Skylark~~ Starlark https://github.com/bazelbuild/starlark

**Comment by arturdryomov** [comment]
YAML is error-prone regarding strings. Technically it is possible to use them without quotes but hell breaks loose easily.

https://stackoverflow.com/a/22235064

> Given all these caveats, I'd rather just use quotes everywhere :-/

I like how it looks though. And we can mitigate the strings issue with samples including quoting.

**Comment by artem-zinnatullin** [comment]
Strings are definitely problematic in YAML, I'll use quotes in examples and tests 👍 

Also, it relies on indentation…
