### ISSUE TITLE
Instrumented unit tests

### ISSUE THREAD

**Issue by guelo** [gojuno/mainframer#228]
Is there any way to run instrumented android tests with mainframer? connectedAndroidTest doesn't work because it tries to start adb on the remote.

**Comment by artem-zinnatullin** [comment]
You can build everything on remote machine for instrumentation tests, appropriate Gradle tasks have `androidTest` in the name

ie

```console
mainframer './gradlew :app:assembleDebug :app:assembleDebugAndroidTest' && run-tests-locally
```

Where `run-tests-locally` is command to run tests on locally connected emulator/device using apks built remotely

**Comment by guelo** [comment]
Has anyone has figured out how to hook into Android Studio's instrumented test runner?

**Comment by artem-zinnatullin** [comment]
What exactly do you mean?

**Comment by guelo** [comment]
I mean an Android Studio Configuration to run Instrumented tests the same way we can do for JUnit tests using `mainframer ./gradlew compileDebugUnitTestSources mockableAndroidJar`

**Comment by artem-zinnatullin** [comment]
In the comment above I've explained how to do it.

Running it just via Mainfraimer will run the tests on remote machine which is likely not what you want, that's why I suggest to use Mainframer to **build** remotely but then run locally using results of the remote build.

**Comment by guelo** [comment]
I don't want to write a script to do the `&& run-tests-locally` part. I want Android Studio to start the emulator, install the apks, show the pretty test results. You have instructions to do that for JVM tests here https://github.com/gojuno/mainframer/tree/development/samples/gradle-android#android-studio-configuration-to-run-junit-tests

 I'd like to have the same thing for Instrumented tests.

**Comment by JayNewstrom** [comment]
I've had a lot of success using https://github.com/elpassion/mainframer-intellij-plugin

Start by running the test normally, then going into the edit run configurations, copying the one that's automatically created when you run a test, and removing the gradle aware make, and replacing it with the mainframer make.

You also have to disable instant run.
