### ISSUE TITLE
How to make configuration for building iOS from non-mac OS local machine?

### ISSUE THREAD

**Issue by RotBolt** [gojuno/mainframer#267]
I am developer who has Linux. But want to build for  iOS apps. How could I use Mainframer to build for iOS from my local machine ?

**Comment by lukeduncan-scot** [comment]
I think you'd probably need to start here and work your way back to mainframer
https://developer.apple.com/library/archive/technotes/tn2339/_index.html

**Comment by akshob** [comment]
@RotBolt You can probably start with [cctools-port](https://github.com/tpoechtrager/cctools-port) which is a cross compiler toolchain that includes building iOS binaries from Linux ([example usage](https://github.com/tpoechtrager/cctools-port/tree/master/usage_examples/ios_toolchain)).

**Comment by artem-zinnatullin** [comment]
Hi @RotBolt, just want to clarify few things so we're on the same page:

- Mainframer doesn't help with setting up coding or build environment, it 1) pushes project files to remote machine 2)  runs arbitrary command like `xcode build` on a remote machine 3) pulls files back from remote machine
- To build iOS app with Mainframer you need remote machine to be either macOS with Xcode build toolchain or be other OS with iOS compatible build toolchain

I'd say best result can be achieved with remote machine being macOS machine (perhaps you have some at work or you can rent a virtual macOS machine from a hosting provider) with Xcode setup and SSH server, then you can run `mainframer xcode build` commands on it while doing coding from your local Linux machine :)

**Comment by artem-zinnatullin** [comment]
Just realized this is quite an old issue that got recent replies, sorry I didn't respond back then, hopefully all the answers in the thread will help someone with similar question.

Closing, but feel free to comment!
