### ISSUE TITLE
Use mainframer folder on a remote machine

### ISSUE THREAD

**Issue by artem-zinnatullin** [gojuno/mainframer#30]
This will help keeping remote home directory `~` clean and easy to navigate through in case of many projects.

**Comment by artem-zinnatullin** [comment]
Huh, looks like it's not that easy. The only 100% working solution I've found is to run `ssh host mkdir -p ~/mainframer` but it requires separate ssh call which I don't want to introduce…

**Comment by Tagakov** [comment]
Why you can't just let rsync create target folder for you?

 You can achieve this by using parameter `--rsync-path="mkdir -p ~/mainframer/ && rsync"`

It is a little hacky but totally valid.
