### ISSUE TITLE
Fix env vars recipe

### ISSUE THREAD

**Issue by artem-zinnatullin** [gojuno/mainframer#33]
https://twitter.com/ckesc/status/812006350385541120

**Comment by ckesc** [comment]
More details:
`.bashrc` is not readed when you execute ssh commands. For example `ssh HOST "printenv"`
See more at 
http://stackoverflow.com/questions/216202/why-does-an-ssh-remote-command-get-fewer-environment-variables-then-when-run-man

**Comment by artem-zinnatullin** [comment]
So we don't have such a recipe now lol, closing this issue.
