### ISSUE TITLE
Linux / OS X tar incompatibility

### ISSUE THREAD

**Issue by ckesc** [gojuno/mainframer#34]
When remote host uncompressing tar it logs a lot of warnings like
```
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
```
**More about this problem:**
http://superuser.com/questions/318809/linux-os-x-tar-incompatibility-tarballs-created-on-os-x-give-errors-when-unt

**Solution:** 
use GNU tar (`gtar`) in mainframer

**Comment by artem-zinnatullin** [comment]
Hm.

>Fortunately, this does NOT affect the files stored in the archive, which are restored perfectly. However, it does cause problems in a number of scenarios, especially when dealing with build processes where the non-zero failure code returned by 'tar' causes builds

Does this cause "build" failure for you or it just prints warnings and everything works good?

We can't use `gtar` that easy because it is not installed on almost any OS nowadays, though we can do similar optional support for it as we did for `pigz` instead of `gzip` #24.

Also, if `rsync` will be better for all cases #22, `tar` won't be required at all.

**Comment by artem-zinnatullin** [comment]
We also use `mainframer` in similar setup: local machines are mostly Mac OS (and one Linux) and remote machine is Ubuntu 16.04 and nobody have seen such warnings.

For example I have `BSD tar` on my Mac OS and on Ubuntu we have `GNU tar`.

**Comment by ckesc** [comment]
No it not fails build.
Optional support will be cool.

I have 
bsdtar 2.8.3 - lib archive 2.8.3 on local OSX
tar (GNU tar) 1.27.1 on remote host Ubuntu 14.04.5 LTS

**Comment by artem-zinnatullin** [comment]
Looks like `rsync` is more better choise, so I guess we'll close this issue by switching to `rsync` :)

**Comment by ming13** [comment]
Most likely was implicitly fixed by #22. @artem-zinnatullin?

**Comment by artem-zinnatullin** [comment]
Yup! Closing for now, @ckesc feel free to reopen with new comments!

**Comment by artem-zinnatullin** [comment]
Forgot to say, please try it on v1.1.0 or later version!
