### ISSUE TITLE
tar: */build: Cannot stat: No such file or directory

### ISSUE THREAD

**Issue by voronnenok** [gojuno/mainframer#36]
My output is...

........................
BUILD SUCCESSFUL

Total time: 2 mins 39.252 secs
+ tar -c --exclude=kotlin --exclude=tmp build/ '*/build'
tar: */build: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors

Process finished with exit code 2

And apk not installs on device

**Comment by ming13** [comment]
`'*/build'` part looks suspicious. [We don’t have it in quotes](https://github.com/gojuno/mainframer/blob/ca85d95a751de322d7d8babd021f2332a0c88f0e/mainframer.sh#L81).

**Comment by artem-zinnatullin** [comment]
On which version of `mainframer` are you? Haven't you edit it yourself? Can you please reattach logs using markdown ```?

**Comment by ming13** [comment]
Most likely was fixed by #22 this way or another.

**Comment by artem-zinnatullin** [comment]
Yes, I also believe so. @voronnenok please try v1.1.0 and report back!

**Comment by voronnenok** [comment]
v1.1.0 is great! Thanks!
