### ISSUE TITLE
Find a better way to read properties

### ISSUE THREAD

**Issue by artem-zinnatullin** [gojuno/mainframer#46]
Currently we use `awk` in a way that sometimes leads to wrong results, for example we will read even commented out properties like:

```properties
#remote_build.machine=value1
remote_build.machine=value2
```

Both values will be grepped for `remote_build.machine`.

**Comment by dmitry-novikov** [comment]
Proposed solution https://github.com/gojuno/mainframer/pull/47

**Comment by artem-zinnatullin** [comment]
Closed by #47.
