### ISSUE TITLE
Automatic Gradle tasks recognition in Android Studio

### ISSUE THREAD

**Issue by ahornerr** [gojuno/mainframer#49]
Hey there!

First of all I want to start by saying what a wonderful tool this is. It will save us hours if not days in compile time!

We support a project with a large number of build variants and it's a bit annoying to have to edit the run configuration each time we want to switch variants. I had a short-term solution of using an Android Studio macro `$Prompt$` to prompt the user which variant they wanted to build, but that must be done each launch.

I dug through the Android Studio files and I found that the module's `.iml` file contains the build variant. Since the `.iml` file is XML, we can easily parse out the build variant for our own use.

### Here's some quick and dirty parsing code I wrote:

```
xmllint --xpath "string(//option[@name='ASSEMBLE_TASK_NAME']/@value)" app/app.iml
```

### Output

```
assemble[my flavor]Debug
```

From here, we can pass this to the mainframer.sh script. Here's what I have:

### Parameters:
```
-c "bash mainframer.sh ./gradlew :app:$(xmllint --xpath \"string(//option[@name='ASSEMBLE_TASK_NAME']/@value)\" app/app.iml) -Pandroid.enableBuildCache=true -PminSdk=23"
```

Hopefully this is of use to someone else! Thanks!

**Comment by ahornerr** [comment]
I believe I found the issue, related to the bash parameter execution, working on a fix.

**Comment by artem-zinnatullin** [comment]
Neat, though we don't have flavors to test this, but it'd be very nice to use something like this to run required gradle tasks automatically, the same Android Studio does using "Gradle-aware Make". But I'm afraid this would require Android Studio plugin.

**Comment by artem-zinnatullin** [comment]
TL;TR: plugin for IntelliJ Idea or Android Studio that will automatically pass required build steps to `mainframer.sh` would be very neat.

If someone would like to start working on this — please ping us here, so community could track your progress!

@ahornerr thanks for sharing your receipe, in v2.0.0 we'll have samples for different build systems and I'll add a link to your receipe into `gradle-android` sample docs!

**Comment by ahornerr** [comment]
Yes, I've noticed that if I don't give Android Studio enough time to update the `.iml` file after switching flavors, it will build the old flavor. Typically this only takes about 10-15 seconds but it's important for me not to jump the gun.

**Comment by ahornerr** [comment]
Thank you!

**Comment by artem-zinnatullin** [comment]
>Yes, I've noticed that if I don't give Android Studio enough time to update the .iml file after switching flavors, it will build the old flavor. Typically this only takes about 10-15 seconds but it's important for me not to jump the gun.

Doesn't it show the progress of Gradle sync that is happening  once you switch between build types/flavors? I believe you simply need to wait until it completes and then start the build.

**Comment by ahornerr** [comment]
That's correct, I'm just impatient :)

**Comment by artem-zinnatullin** [comment]
Haha, that's understandable 😸

**Comment by edwardstock** [comment]
Nice solution!

By the same way, can take gradle options from: .idea/workspace.xml
```bash
xmllint --xpath "string(//option[@name='COMMAND_LINE_OPTIONS']/@value)" .idea/workspace.xml
```
