### ISSUE TITLE
Extract config parameters to a separate file instead of using local.properties

### ISSUE THREAD

**Issue by artem-zinnatullin** [gojuno/mainframer#50]
Since 2.x will already be breaking #19, we can also extract mainframer config parameters to a separate file since Android Studio adds not very funny header to `local.properties` (though I've never saw such behavior):

```
## This file is automatically generated by Android Studio.
# Do not modify this file -- YOUR CHANGES WILL BE ERASED!
```

Something like `.mainframerconfig` should be fine I think.

**Comment by ibit** [comment]
@artem-zinnatullin the config file option should be probably updated in the README file

**Comment by artem-zinnatullin** [comment]
Sure, we'll update README before v2.0.0 release, it's still in development at the moment, created #72 to track this.
