### ISSUE TITLE
Usage of Instant Run

### ISSUE THREAD

**Issue by bresan** [gojuno/mainframer#53]
Hey guys, it's being really amazing how much my old 2010 MBP is not freezing anymore due to this project and remote builds, thanks for everything 👍 

Does anyone was able to run the project using the feature of Instant Run? I think it would be a really great feature, since it does reduce a lot the time of builds (at least for me is pretty evident the difference).

I have checked some discussions around, and have found this one (https://code.google.com/p/android/issues/detail?id=199609) in Google Discussions, saying that they don't give support to Instant Run outside of the Android Studio IDE. Does anyone know some workaround for this?

Thanks for the help, and one more time for the amazing project!

**Comment by null-dev** [comment]
I tried it and it seemed to work no problem. I did no extra configuration.

**Comment by bresan** [comment]
Woah.. really? On mine it doesn't look like it's working, at least the dialog of the instant run is not displayed.

What are you sending on arguments to the mainframer? Mine currently is `mainframer.sh ./gradlew :app:assembleDebug -Pmin.sdk.version=21 -Pandroid.enableBuildCache=true`, but I don't think this is supposed to cause this issue.

**Comment by null-dev** [comment]
Wait, there is an instant run dialog? Do you mean the dialog that lets you select what device to deploy to?

**Comment by bresan** [comment]
No no, the little green pop up that is displayed on the IDE (like this: http://www.techotopia.com/images/b/b9/Android_studio_2_instant_run_full_build.png, but with the text of instant run done etc etc). 

Yeah, it is checked as well the instant run option, so I'm kinda lost on this. Can you put here your arguments for mainframer? Also, I have multiDex enable on the project, and was thinking this could be one of the reasons behind it.

**Comment by null-dev** [comment]
Mine are just: `mainframer.sh ./gradlew :app:assembleStandardDebug`. I use product flavors so don't worry about `Standard`.

Instant run works for me:
![instant-run](https://cloud.githubusercontent.com/assets/9571936/21648543/5af256c6-d26c-11e6-946a-338fa4f9b178.png)

Does your app fall into the "Legacy Multidex" criteria here: https://developer.android.com/studio/run/index.html#ir-limitations?

**Comment by null-dev** [comment]
Instant run works fine with Kotlin for me:
![instant-run-kt](https://cloud.githubusercontent.com/assets/9571936/21649016/29b35388-d26e-11e6-9e84-629b76f645a5.png)

Maybe I'm just a very lucky guy.

**Comment by Tagakov** [comment]
Instant run doesn't work because it can't be run from the command line. Although the icon near the play button appears and indicates that Instant Run works on the mainframe side full incremetal build always happens.

**Comment by rodrigobressan** [comment]
Oh :( I really hope someday we can use it together with Instant Run, since it looks like it's something built in Android Studio and not from command line, as @Tagakov pointed out.

Well, thanks for the answers (and sorry for the delay on the reply). Amazing project guys!

**Comment by artem-zinnatullin** [comment]
I'm closing this issue for now.

Summing up: Since Instant Run deeply integrated into Android Studio (and Gradle) and cannot be used from command line, we can not offer Mainframer integration with Instant Run at this moment.

Please feel free to comment, add more info or invite guys from Android Developer Tools team or JRebel to this discussion.

**Comment by satanyakiv** [comment]
Hi there!

I'm very new in mainframer setup... 

Does anything changed with Instant Run for now? 

@artem-zinnatullin

**Comment by arturdryomov** [comment]
Nope, nothing new on this. Instant Run is IDE feature only, so no offloading to a separate machine will help you with this. At least I think so, since I’m not using IR at all.
