### ISSUE TITLE
Add separate folder for mainframer configs

### ISSUE THREAD

**Issue by artem-zinnatullin** [gojuno/mainframer#54]
In v2.x we'll add several files #19, #51 to allow customizations and integrations with basically *any* build system, also we're planning to move away from `local.properties` #50.

With that in mind, there is an option to put all mainframer configs into a separate folder (eg `mainframer`) where we could store all required files:

* `ignorelocal` (should be under VCS in most cases)
* `ignoreremote`(should be under VCS in most cases)
* `personalconfig` (or `config` (should NOT be under VCS in most cases)

**Comment by artem-zinnatullin** [comment]
@ming13, @dmitry-novikov thoughts?

**Comment by ming13** [comment]
This structure should fit.
```
.mainframer/localignore
.mainframer/remoteignore
.mainframer/config
```
