### ISSUE TITLE
Allow different sdk.dir property for the remote machine

### ISSUE THREAD

**Issue by ibit** [gojuno/mainframer#71]
My remote machine skd path is different than my local one.
I would like to be able to set the remote sdk path separately so my local machine will still work as intended. 

For version 1.1.1 I passed the sdk path as an argument 'ANDROID_HOME=path/to/sdk'
Since 1.1.2 this workaround no longer work

**Comment by artem-zinnatullin** [comment]
`mainframer` does not know about `sdk.dir`.

How do you download `mainframer.sh` to include it into your project? I believe you've downloaded it right from master branch where we have unreleased version.

**Comment by ibit** [comment]
I did download the mainframer.sh from the master branch. I see now that the release one is different.
Personally, I would keep the master aligned with the release and branch out for development

**Comment by artem-zinnatullin** [comment]
We'll rename `master` to `dev` 😸 to avoid confusion.

We have download instructions in README, please follow them!
