### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by artem-zinnatullin** [gojuno/mainframer#8]
We can try to `ssh` to the same machine that runs CI build (Travis, CircleCI, etc) and then run some Gradle build and check its results.

**Comment by panpanini** [comment]
To me it sounds like that might defeat the purpose of the project - from how I interpret it the project is designed to speed up builds, however if we have to wait for CI to check each build it could end up blowing out the build times to back where they originally were

**Comment by artem-zinnatullin** [comment]
Haha, nononono, @panpanini, I meant add CI for **this** (GitHub) project so we could test it continuosly, not for the remote builds themselves! 😸

**Comment by panpanini** [comment]
doh! that makes way more sense haha

**Comment by artem-zinnatullin** [comment]
Ok, #26 definitely shown that we need CI for `mainframer`, I have couple options in mind, will try to implement them in near future.

**Comment by artem-zinnatullin** [comment]
We need it, working on it.
