### ISSUE TITLE
Optional pigz integration

### ISSUE THREAD

**Issue by ming13** [gojuno/mainframer#9]
`pigz` works in parallel and in our case does compression faster for a large number of output files.

**Comment by artem-zinnatullin** [comment]
Let's add this in v1.0.1, disabling compression saves about 2 seconds for @dmitry-novikov on gigabit ethernet connection. 

At the same time, disabling compression adds about 2 seconds for me on `ac` wifi connection, switching to `pigz` saves about 2 seconds back lol.

**Comment by ming13** [comment]
Just run some variations on MacBook Pro (Retina, 13-inch, Early 2015) without command execution timing, i. e. always packaging same sources and results. Using the local network.

| Description | Avg. Time, s |
|------------|------------|
| gzip + compression 0 | 8 |
| gzip + compression 1 | 9 |
| gzip + compression 4 | 9 |
| pigz + compression 1 | 7 |
| pigz + compression 4 | 6 |
| pigz + compression 6 | 7 |
| bonus: pipe for scp and tar | 9 |

**Comment by artem-zinnatullin** [comment]
K, let's add optional `pigz` support for both local and remote machines and add it to performance optimizations tips and instruction for remote machine setup!
